/* This file is autogenerated. Do not edit by hand! */

namespace EvershockGame.Code
{

    //---------------------------------------------------------------------------

    public enum EAllAssets
    {
        WalkingAnimation1,
    }

    //---------------------------------------------------------------------------

    public enum ESpriteAssets
    {
        WalkingAnimation1,
    }

    //---------------------------------------------------------------------------

    public enum ETilesetAssets
    {
    }

    //---------------------------------------------------------------------------

    public enum EEffectAssets
    {
        WalkingAnimation1,
    }
}