//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvershockGame.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvershockGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ItemPools {
            get {
                return ResourceManager.GetString("ItemPools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [
        ///  {
        ///    &quot;Name&quot;: &quot;Potion&quot;,
        ///    &quot;Type&quot;: &quot;HealthPotion&quot;,
        ///    &quot;Rarity&quot;: &quot;Common&quot;,
        ///    &quot;Category&quot;: &quot;Usable&quot;,
        ///    &quot;SpriteX&quot;: 7,
        ///    &quot;SpriteY&quot;: 2,
        ///    &quot;IsStackable&quot;: true
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Axe&quot;,
        ///    &quot;Type&quot;: &quot;Axe&quot;,
        ///    &quot;Rarity&quot;: &quot;Epic&quot;,
        ///    &quot;Category&quot;: &quot;Usable&quot;,
        ///    &quot;SpriteX&quot;: 9,
        ///    &quot;SpriteY&quot;: 7,
        ///    &quot;IsStackable&quot;: false
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Small key&quot;,
        ///    &quot;Type&quot;: &quot;SmallKey&quot;,
        ///    &quot;Rarity&quot;: &quot;Rare&quot;,
        ///    &quot;Category&quot;: &quot;Usable&quot;,
        ///    &quot;SpriteX&quot;: 7,
        ///    &quot;SpriteY&quot;: 16,
        ///    &quot;IsStackable&quot;: tr [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
    }
}
